

import React, { useState } from "react";
import jsPDF from "jspdf";
import { saveAuditLog } from "../utils/tempLog2"; 
type MaterialItem = {
  materialName: string;
  quantity: number;
  unit: string;
  note?: string;
};
const ProformaPage = () => {
  const [supplier, setSupplier] = useState("");
  const [requestDate, setRequestDate] = useState("");
  const [materialName, setMaterialName] = useState("");
  const [quantity, setQuantity] = useState("");
  const [unit, setUnit] = useState("pcs");
  const [note, setNote] = useState("");
  const [items, setItems] = useState<MaterialItem[]>([]);
  const [pdfUrl, setPdfUrl] = useState<string | null>(null);
  const addItem = () => {
    const qty = Number(quantity);
    if (!materialName.trim() || qty <= 0) {
      alert("Enter material and quantity");
      return;
    }
    setItems([
      ...items,
      {
        materialName: materialName.trim(),
        quantity: qty,
        unit,
        note,
      },
    ]);
    setMaterialName("");
    setQuantity("");
    setUnit("pcs");
    setNote("");
  };
  const removeItem = (index: number) => {
    setItems(items.filter((_, i) => i !== index));
  };
  const generatePDF = () => {
    if (!supplier.trim() || !requestDate || items.length === 0) {
      alert("Fill supplier, date, and add materials");
      return;
    }
    const doc = new jsPDF();
    let y = 20;
    doc.setFontSize(18);
    doc.setFont("helvetica", "bold");
    doc.text("MATERIAL PURCHASE REQUEST", 105, y, { align: "center" });
    y += 12;
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Supplier / Vendor: ${supplier}`, 20, y);
    y += 8;
    doc.text(`Date: ${new Date(requestDate).toLocaleDateString()}`, 20, y);
    y += 12;
    doc.line(20, y, 190, y);
    y += 10;
    doc.setFillColor(241, 245, 249);
    doc.rect(20, y - 6, 170, 10, "F");
    doc.setFont("helvetica", "bold");
    doc.text("Material", 22, y);
    doc.text("Qty", 95, y);
    doc.text("Unit", 120, y);
    doc.text("Note", 145, y);
    y += 10;
    doc.setFont("helvetica", "normal");
    items.forEach((item) => {
      if (y > 265) {
        doc.addPage();
        y = 20;
      }
      const materialLines = doc.splitTextToSize(item.materialName, 65);
      const noteLines = doc.splitTextToSize(item.note || "N/A", 45);
      doc.text(materialLines, 22, y);
      doc.text(String(item.quantity), 95, y);
      doc.text(item.unit, 120, y);
      doc.text(noteLines, 145, y);
      y += Math.max(materialLines.length, noteLines.length) * 6 + 4;
      doc.line(20, y - 3, 190, y - 3);
    });
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("Message:", 20, y);
    y += 7;
    doc.setFont("helvetica", "normal");
    doc.text(
      doc.splitTextToSize(
        "Please send us a proforma invoice for the materials listed above.",
        170
      ),
      20,
      y
    );
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(9);
    doc.text("Generated by ERP System", 105, pageHeight - 10, {
      align: "center",
    });
    if (pdfUrl) {
      URL.revokeObjectURL(pdfUrl);
    }
    const url = URL.createObjectURL(doc.output("blob"));
    setPdfUrl(url);
  };
  const newProforma = () => {
    setSupplier("");
    setRequestDate("");
    setMaterialName("");
    setQuantity("");
    setUnit("pcs");
    setNote("");
    setItems([]);
    if (pdfUrl) {
      URL.revokeObjectURL(pdfUrl);
      setPdfUrl(null);
    }
  };
  const printPDF = () => {
    const iframe = document.getElementById("proformaFrame") as HTMLIFrameElement;
    iframe?.contentWindow?.print();
  };
  return (
    <div style={styles.page}>
      <div style={styles.card}>
        <h1 style={styles.title}>Material Purchase Request</h1>
        <p style={styles.subtitle}>Prepare request to send for proforma</p>
        <div style={styles.grid}>
          <input
            style={styles.input}
            placeholder="Supplier / Vendor Name"
            value={supplier}
            onChange={(e) => setSupplier(e.target.value)}
          />
          <input
            style={styles.input}
            type="date"
            value={requestDate}
            onChange={(e) => setRequestDate(e.target.value)}
          />
        </div>
        <div style={styles.itemBox}>
          <h3>Add Material</h3>
          <div style={styles.grid}>
            <input
              style={styles.input}
              placeholder="Material name"
              value={materialName}
              onChange={(e) => setMaterialName(e.target.value)}
            />
            <input
              style={styles.input}
              type="number"
              placeholder="Quantity"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
            />
            <select
              style={styles.input}
              value={unit}
              onChange={(e) => setUnit(e.target.value)}
            >
              <option value="pcs">pcs</option>
              <option value="box">box</option>
              <option value="kg">kg</option>
              <option value="gal">gal</option>
              <option value="meter">meter</option>
              <option value="liter">liter</option>
            </select>
          </div>
          <textarea
            style={styles.textarea}
            placeholder="Note / specification"
            value={note}
            onChange={(e) => setNote(e.target.value)}
          />
          <button style={styles.addBtn} onClick={addItem}>
            Add Material
          </button>
        </div>
        <div style={styles.tableWrap}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>Material</th>
                <th style={styles.th}>Qty</th>
                <th style={styles.th}>Unit</th>
                <th style={styles.th}>Note</th>
                <th style={styles.th}>Action</th>
              </tr>
            </thead>
            <tbody>
              {items.length === 0 ? (
                <tr>
                  <td colSpan={5} style={styles.empty}>
                    No materials added
                  </td>
                </tr>
              ) : (
                items.map((item, index) => (
                  <tr key={index}>
                    <td style={styles.td}>{item.materialName}</td>
                    <td style={styles.td}>{item.quantity}</td>
                    <td style={styles.td}>{item.unit}</td>
                    <td style={styles.td}>{item.note || "N/A"}</td>
                    <td style={styles.td}>
                      <button
                        style={styles.removeBtn}
                        onClick={() => removeItem(index)}
                      >
                        Remove
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
        <button style={styles.submitBtn} onClick={generatePDF}>
          Generate Proforma PDF
        </button>
        {pdfUrl && (
          <div style={styles.pdfBox}>
            <iframe
              id="proformaFrame"
              src={pdfUrl}
              width="100%"
              height="520"
              style={styles.iframe}
            />
            <div style={styles.pdfActions}>
              <button style={styles.newBtn} onClick={newProforma}>
                New Proforma
              </button>
              <button style={styles.printBtn} onClick={printPDF}>
                Print
              </button>
              <button
                style={styles.closeBtn}
                onClick={() => {
                  URL.revokeObjectURL(pdfUrl);
                  setPdfUrl(null);
                }}
              >
                Close
              </button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
};
export default ProformaPage;
const styles: any = {
  page: {
    minHeight: "100vh",
    background: "#f3f6fb",
    padding: "35px 24px",
    fontFamily: "Arial, sans-serif",
  },
  card: {
    maxWidth: "1100px",
    margin: "0 auto",
    background: "#fff",
    borderRadius: "22px",
    padding: "28px",
    boxShadow: "0 18px 40px rgba(15,23,42,0.12)",
  },
  title: {
    margin: 0,
    fontSize: "36px",
    color: "#0f172a",
  },
  subtitle: {
    color: "#64748b",
    marginTop: "6px",
    marginBottom: "22px",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "14px",
  },
  input: {
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
    outline: "none",
  },
  itemBox: {
    marginTop: "24px",
    padding: "20px",
    borderRadius: "18px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
  },
  textarea: {
    width: "100%",
    minHeight: "90px",
    marginTop: "14px",
    padding: "14px",
    borderRadius: "14px",
    border: "1px solid #cbd5e1",
    fontSize: "16px",
    outline: "none",
    boxSizing: "border-box",
  },
  addBtn: {
    marginTop: "14px",
    border: "none",
    borderRadius: "12px",
    background: "#2563eb",
    color: "#fff",
    padding: "12px 18px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  tableWrap: {
    marginTop: "24px",
    border: "1px solid #e2e8f0",
    borderRadius: "16px",
    overflowX: "auto",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    background: "#f1f5f9",
    padding: "14px",
    textAlign: "left",
  },
  td: {
    padding: "13px 14px",
    borderTop: "1px solid #e2e8f0",
  },
  empty: {
    padding: "28px",
    textAlign: "center",
    color: "#64748b",
  },
  removeBtn: {
    border: "none",
    borderRadius: "10px",
    background: "#dc2626",
    color: "#fff",
    padding: "8px 12px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  submitBtn: {
    marginTop: "24px",
    width: "100%",
    border: "none",
    borderRadius: "14px",
    background: "#16a34a",
    color: "#fff",
    padding: "15px",
    fontSize: "17px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  pdfBox: {
    marginTop: "25px",
    background: "#f8fafc",
    border: "1px solid #e2e8f0",
    borderRadius: "16px",
    padding: "16px",
  },
  iframe: {
    border: "1px solid #cbd5e1",
    borderRadius: "12px",
    background: "#fff",
  },
  pdfActions: {
    marginTop: "12px",
    display: "flex",
    gap: "10px",
  },
  newBtn: {
    border: "none",
    borderRadius: "10px",
    background: "#2563eb",
    color: "#fff",
    padding: "10px 14px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  printBtn: {
    border: "none",
    borderRadius: "10px",
    background: "#16a34a",
    color: "#fff",
    padding: "10px 14px",
    fontWeight: "bold",
    cursor: "pointer",
  },
  closeBtn: {
    border: "none",
    borderRadius: "10px",
    background: "#dc2626",
    color: "#fff",
    padding: "10px 14px",
    fontWeight: "bold",
    cursor: "pointer",
  },
};